version: "3.8"
services:
  invoice-generator:
    build: .
    container_name: invoice-generator
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
      - SQLALCHEMY_DATABASE_URI=sqlite:///database.db
    volumes:
      - ./database.db:/app/database.db
    networks:
      - flask-network